const express = require("express")
const cors=require("cors")
const app = express()
app.use(cors())
const bodyParser = require("body-parser")
app.use(bodyParser.json())
app.listen(4040, () => { console.log("server run on port 4040") })
const api=require("./API")
api.init(app)